version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]